name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    env:
      TMS_PRIVATE_TOKEN: ${{ secrets.TMS_PRIVATE_TOKEN }}
      TMS_URL: ${{ vars.TMS_URL }}
      TMS_PROJECT_ID: ${{ vars.TMS_PROJECT_ID }}
      TMS_CONFIGURATION_ID: ${{ vars.TMS_CONFIGURATION_ID }}
      TMS_ADAPTER_MODE: ${{ vars.TMS_ADAPTER_MODE }}
      TMS_AUTOMATIC_CREATION_TEST_CASES: ${{ vars.TMS_AUTOMATIC_CREATION_TEST_CASES }}
      TMS_AUTOMATIC_UPDATION_LINKS_TO_TEST_CASES: ${{ vars.TMS_AUTOMATIC_UPDATION_LINKS_TO_TEST_CASES }}
      MT_VALID_EMAIL: ${{ vars.MT_VALID_EMAIL }}
      MT_VALID_PASSWORD: ${{ vars.MT_VALID_PASSWORD }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm install -g yarn && yarn
    - name: Install Playwright Browsers
      run: yarn playwright install --with-deps
    - name: Run Playwright tests
      run: yarn playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
